# Generated by Django 6.1.2 on 2026-10-06 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('app', 'App')], max_length=10)),
                ('cuerpo_plantilla', models.TextField()),
            ],
            options={
                'db_table': 'plantilla',
                'constraints': [models.CheckConstraint(condition=models.Q(('canal__in', ['email', 'sms', 'push', 'app'])), name='chk_plantilla_canal')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_asegurado', models.UUIDField()),
                ('id_siniestro', models.UUIDField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('app', 'App')], max_length=10)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField()),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(blank=True, db_column='id_plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='notificaciones.plantilla')),
            ],
            options={
                'db_table': 'notificacion',
                'indexes': [models.Index(fields=['id_asegurado'], name='idx_notificacion_asegurado'), models.Index(fields=['sent_at'], name='idx_notificacion_sent_at'), models.Index(fields=['status'], name='idx_notificacion_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('canal__in', ['email', 'sms', 'push', 'app'])), name='chk_notificacion_canal'), models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'enviado', 'fallido'])), name='chk_notificacion_status')],
            },
        ),
    ]
