services:
  notification_service:
    build: .
    container_name: notification_service
    ports:
      - "8006:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notification_db
      REDIS_URL: redis://redis:6379/0
    env_file:
      - path: .env
        required: false
    depends_on:
      - postgres
      - redis

  notification_worker:
    build: .
    container_name: notification_worker
    command: celery -A comun.celery_app worker -Q notification --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notification_db
      REDIS_URL: redis://redis:6379/0
    env_file:
      - path: .env
        required: false
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: notification_db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: notification_redis
    ports:
      - "6385:6379"

volumes:
  postgres_data:
